# cksum
# Autogenerated from man page /usr/share/man/man1/cksum.1.bz2
complete -c cksum -l help -d 'display this help and exit'
complete -c cksum -l version -d 'output version information and exit AUTHOR Written by Q.  Frank Xia'

