# eselect
# Autogenerated from man page /usr/share/man/man1/eselect.1.bz2
complete -c eselect -l brief -d 'Set brief output mode, for use as input to other programs'
complete -c eselect -l color -l colour -d 'Enable or disable colour output.  mode can be yes , no , or auto '

