# kpsereadlink
# Autogenerated from man page /usr/share/man/man1/kpsereadlink.1.bz2
complete -c kpsereadlink -l help -d 'Print help message and exit'
complete -c kpsereadlink -l version -d 'Print version information and exit'

