# kpseaccess
# Autogenerated from man page /usr/share/man/man1/kpseaccess.1.bz2
complete -c kpseaccess -l help -d 'Print help message and exit'
complete -c kpseaccess -l version -d 'Print version information and exit'

