# npx
# Autogenerated from man page /usr/share/man/man1/npx.1.bz2
complete -c npx -s p -l package -l package -d 'o 2'
complete -c npx -l no-install -d 'o 2'
complete -c npx -l cache -d 'o 2'
complete -c npx -l userconfig -d 'o 2'
complete -c npx -s c -d 'o 2'
complete -c npx -l shell -d 'o 2'
complete -c npx -l shell-auto-fallback -d 'o 2'
complete -c npx -l ignore-existing -d 'o 2'
complete -c npx -s q -l quiet -d 'o 2'
complete -c npx -s n -l node-arg -d 'o 2'
complete -c npx -s v -l version -d 'EXAMPLES Running a project-local bin $ npm i -D webpack $ npx webpack '

