# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8.bz2
complete -c shutdown -s a -d 'Use /etc/shutdown. allow. \\"}}} . \\"{{ -k'
complete -c shutdown -s k -d 'Don\'t really shutdown; only send the warning messages to everybody. \\"}}} '
complete -c shutdown -s r -d 'Reboot after shutdown. \\"}}} . \\"{{ -h'
complete -c shutdown -s h -d 'Equivalent to -P, unless -H is specified. \\"}}} . \\"{{ -P'
complete -c shutdown -s P -d 'Halt action is to turn off the power. \\"}}} . \\"{{ -H'
complete -c shutdown -s H -d 'Action is to halt or drop into boot monitor on systems that support it'
complete -c shutdown -s f -d 'Skip fsck on reboot. \\"}}} . \\"{{ -F'
complete -c shutdown -s F -d 'Force fsck on reboot. \\"}}} . \\"{{ -n'
complete -c shutdown -s n -d '[DEPRECATED] Don\'t call init(8) to do the shutdown but do it ourself'
complete -c shutdown -s c -d 'Cancel a waiting shutdown.  ("shutdown now" is no longer waiting'
complete -c shutdown -s q -d 'Reduce the number of warnings shutdown displays'
complete -c shutdown -s Q -d 'Silence warnings prior to shutting down'
complete -c shutdown -s t -d 'Tell init(8) to wait sec seconds between sending all processes the warning (S…'

