# syslogd
# Autogenerated from man page /usr/share/man/man8/syslogd.8.bz2
complete -c syslogd -s 4 -d 'Force syslogd to use IPv4 addresses only'
complete -c syslogd -s 6 -d 'Force syslogd to use IPv6 addresses only'
complete -c syslogd -s A -d 'Ordinarily, syslogd tries to send the message to only one address even if the…'
complete -c syslogd -s a -d 'Allow peers to log to this syslogd using UDP datagrams'
complete -c syslogd -s d -d 'Put syslogd into debugging mode'
complete -c syslogd -s f -d 'Specify the path name of an alternate configuration file; the default is /etc…'
complete -c syslogd -s F -d 'Run syslogd in the foreground, rather than going into daemon mode'
complete -c syslogd -s k -d 'Disable the translation of messages received with facility kern to facility u…'
complete -c syslogd -s m -d 'Select the number of minutes between mark messages; the default is 20 minutes'
complete -c syslogd -s n -d 'Disable DNS query for every request'
complete -c syslogd -s p -d 'Specify the path name of an alternate log socket to be used instead; the defa…'
complete -c syslogd -s P -d 'Specify an alternative file in which to store the process ID'
complete -c syslogd -s r -d 'Enable built-in support for log rotation of files listed in /etc/syslog. conf'
complete -c syslogd -s s -d 'Operate in secure mode.   Do not log messages from remote machines'
complete -c syslogd -s T -d 'Always use the local time and date for messages received from the network, in…'
complete -c syslogd -s v -d 'Verbose logging'

