# uxterm
# Autogenerated from man page /usr/share/man/man1/uxterm.1.bz2
complete -c uxterm -o class -d and
complete -c uxterm -o u8 -d 'options should not be specified because they are used by the wrapper'

