# xkbcli
# Autogenerated from man page /usr/share/man/man1/xkbcli.1.bz2
complete -c xkbcli -o '\\-help' -d 'Print help and exit'
complete -c xkbcli -o '\\-version' -d 'Print the version and exit El COMMANDS -tag -width Ds compile\\-keymap Compile…'

